apiVersion: apps/v1
kind: Deployment
metadata:
  name: verge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verge
  template:
    metadata:
      labels:
        app: verge
    spec:
      containers:
      - name: verge
        image: verge
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
